### ISSUE TITLE
Warning for invalid directories

### ISSUE THREAD

**Issue by kelunik** [MacFJA/PharBuilder#20]
I'm currently getting the following warning:

![image](https://cloud.githubusercontent.com/assets/2743004/14067193/458b2754-f45f-11e5-86a4-c432baaaa10d.png)

`info` is created in a `build.before` event hook. Seems like the validation happens before hooks are executed.

**Comment by MacFJA** [comment]
You right, `build.before` is call after parsing all arguments/composer data.

I can add a new event before starting parsing arguments (just after getting the `composer.json` file path)

**Comment by kelunik** [comment]
Why not just move the event? Instead of creating a new one?

**Comment by MacFJA** [comment]
For several reason:
- It's doesn't cost anything to add a new event
- For the same reason I use a true event dispatcher instead of function hook: Extendability
- `build.before` happen just the actual build, and the event contains all parsed arguments.

For now, event action are only shell script, but I want to add the same mechanism of composer: have both PHP callable and shell script

**Comment by kelunik** [comment]
Yes, but I'd expect `build.before` to happen _before_ any other thing. Which other name do you suggest for the new event?

I'd go with something like
- dispatch `build.before`
- parse and validate args
- dispatch `build.init` / `build.validate(d)`
- build phar
- dispatch `build.after`

On the other hand: `build.init` is strange after `build.before`. Maybe `build.start`?

**Comment by MacFJA** [comment]
What I have in my mind was `parsing.before`.

But you pointing out that my previous choice was not very wise.
Let's find something better. 😁 

Here my suggestion:
- trigger `application.start`
  - Start the application
  - System check
  - Command init
- trigger `parsing.start` (**`package`** command only)
  - Read argument from CLI argument, Composer data, then ask
- trigger `parsing.end`
- trigger `building.start`
  - Create the PHAR archive
- trigger `building.end`
- trigger `application.end`

**Comment by kelunik** [comment]
I prefer `build` instead of `building`. `application.start` might be problematic if you add more commands like an `about` command or so.

I don't know if we want to consider that edge case, but we might want to run certain `end` hooks when the app is interrupted using `Ctrl + C`.

**Comment by MacFJA** [comment]
`build` instead of `building`: OK
`application.start` (and `application.end`): I see your concerne, and it's too early to add them, I need more time to find the right way to add them.

For `Ctrl-C`, Symfony Console don't handle a such case but it's don't seem to hard to add, but it will not work on Windows

**Comment by kelunik** [comment]
How about `command.[build|package].[start|end]`? I don't think we should emit events for parsing parameters.

**Comment by MacFJA** [comment]
Nice one ! 👍 

When should we trigger the start event ?
I need at least to know where is the `composer.json` file to set the working directory of the shell script (because PharBuilder can be used as an external tool, so the current directory is not necessary the project root)

**Comment by kelunik** [comment]
Sure, you also need the `composer.json` to know which events can even be triggered.
