### ISSUE TITLE
Double slash not handled properly

### ISSUE THREAD

**Issue by Remo** [MacFJA/PharBuilder#49]
I tried to package this library https://github.com/kzykhys/Ciconia

Ended with this message:
```
[BadMethodCallException]
  Entry src//Ciconia/Ciconia.php does not exist and cannot be created: phar error: invalid path "src//Ciconia/Ciconia.php" contains double slash
```

It was easy to fix, just had to remove the / after src in composer.json, but maybe it would be nice if this was handled automatically.

**Comment by PeeHaa** [comment]
@Remo are you on windows by any chance?

**Comment by Remo** [comment]
@PeeHaa yes, I am

**Comment by PeeHaa** [comment]
I am not 100% sure, but I may have already fixed this in master @MacFJA @Remo 

I will double check with the library in OP and report back.

**Comment by PeeHaa** [comment]
I just checked @Remo and it seems like my fix earlier indeed targeted the same issue as you are currently having. Can you try it again on master and report back the result please?

FYI this is the fix https://github.com/MacFJA/PharBuilder/commit/139b51a889dba210ea89ba64188547b84494bb40

The issue was that it only stripped the OS specific directory separator leaving forward slashes under Windows in the path and after it adding files to the path including again a directory separator.

**Comment by Remo** [comment]
@PeeHaa looks good, thanks
